teams:
- name: lockness-maintainers
  maintainers:
  - ryjones
  members:
  - survived
  - maurges
  - ncornwell
- name: lf-staff
  maintainers:
  - ryjones
  members:
  - SeanBohan
  - daniela-barbosa
  - davidwboswell
  - hartm
  - minyu66
  - thelinuxfoundation
  - tykeal
- name: community
  maintainers:
  - ryjones
  members:
  - hartm
  - tkuhrt
repositories:
- name: governance
  teams:
    community: maintain
  visibility: public
